// All user-facing text lives here so another language or a feminine variant can be added later.
export const he = {
  appName: "TradePath IL",
  nav: {
    label: "ניווט ראשי",
    today: "היום",
    roadmap: "מפת דרך",
    lab: "מעבדה",
    journal: "יומן",
  },
  theme: { toggle: "החלף בין מצב בהיר למצב כהה" },
  signOut: "יציאה",
  skipToContent: "דלג לתוכן",
  notFound: {
    title: "העמוד לא נמצא",
    body: "הכתובת שגויה, או שהעמוד הועבר.",
    home: "חזרה לעמוד הראשי",
  },
  error: {
    title: "משהו השתבש",
    body: "לא הצלחנו לטעון את העמוד. ההתקדמות שלך שמורה.",
    retry: "נסה שוב",
  },
  disclaimer:
    "התוכן כאן לימודי בלבד ואינו ייעוץ השקעות או שיווק השקעות. מסחר כרוך בסיכון, ורוב הסוחרים הפרטיים מפסידים כסף.",
  common: {
    minutes: "דקות",
    minutesShort: "דק׳",
    weeks: "שבועות",
    week: "שבוע",
    stage: "שלב",
    lesson: "שיעור",
    module: "מודול",
    reset: "התחל מחדש",
    next: "הבא",
    back: "חזרה",
    check: "בדוק",
    reveal: "גלה",
    continue: "המשך",
    close: "סגור",
    save: "שמור",
    saving: "שומר...",
    saved: "נשמר.",
    saveFailed: "השמירה נכשלה. נסה שוב.",
    correct: "נכון",
    wrong: "לא נכון",
    of: "מתוך",
    previewOnly: "תצוגה לפיתוח בלבד. ההתקדמות לא נשמרת.",
    locked: "נעול",
    done: "הושלם",
    available: "זמין",
    unwritten: "עוד לא נכתב",
    comingInPhase: (phase: number) => `ייבנה בשלב בנייה ${phase}`,
    seeGlossary: "למילון המונחים",
    loading: "טוען...",
    signInRequired: "צריך להתחבר כדי לשמור.",
  },
  today: {
    title: "היום",
    greeting: "מה הצעד הבא שלך",
    nextLesson: "השיעור הבא",
    startLesson: "התחל שיעור",
    continueLesson: "המשך שיעור",
    gateOpen: "השער פתוח",
    gateBody: (stage: number) => `סיימת את כל שיעורי שלב ${stage}. עבור את השער כדי לפתוח את השלב הבא.`,
    goToGate: "לשער",
    waitingForContent: "סיימת כל מה שנכתב עד עכשיו",
    waitingForContentBody: "השיעורים הבאים עוד נכתבים. בינתיים חזור על הכרטיסיות.",
    allDone: "סיימת את כל השיעורים",
    cardsDue: "כרטיסיות לחזרה",
    cardsDueCount: (n: number) => (n === 0 ? "אין כרטיסיות לחזרה היום" : n === 1 ? "כרטיסייה אחת מחכה" : `${n} כרטיסיות מחכות`),
    reviewCards: "לחזרה",
    noCardsYet: "הכרטיסיות הראשונות ייכנסו לחפיסה כשתסיים שיעור.",
    weeklyGoal: "יעד שבועי",
    weeklyGoalBody: (done: number, goal: number) => `${done} מתוך ${goal} דקות השבוע`,
    streak: "רצף שבועות",
    streakBody: (n: number) => (n === 0 ? "עוד אין רצף. שיעור אחד השבוע מתחיל אותו." : n === 1 ? "שבוע אחד ברצף" : `${n} שבועות ברצף`),
    glossaryLink: "מילון המונחים",
    emptyTitle: "עוד אין כאן שיעורים",
    emptyBody: "כשהשיעורים ייטענו, תראה כאן מה הצעד הבא שלך.",
  },
  roadmap: {
    title: "מפת דרך",
    empty: "מפת השלבים והשיעורים תופיע כאן.",
    intro: "8 שלבים, 74 שיעורים, שער בסוף כל שלב. השלב הבא נפתח רק אחרי השער.",
    weeksLeft: (n: number) => (n === 0 ? "סיימת את כל השיעורים שנכתבו" : `כ-${n} שבועות נותרו בקצב שלך`),
    lessonsDone: (done: number, total: number) => `${done} מתוך ${total} שיעורים`,
    gate: "שער",
    gatePassed: "השער עבר",
    gateOpen: "השער פתוח",
    gateLocked: "השער נעול",
    gatePartial: "השער בעבודה",
    stageLocked: "השלב נעול עד שתעבור את השער הקודם",
    volatileMark: "מכיל עובדות שמתעדכנות",
    weeks: (n: number) => `כ-${n} שבועות`,
    unwritten: "עוד לא נכתב",
  },
  lesson: {
    objectives: "בסוף השיעור תדע",
    minutes: (n: number) => `${n} דקות`,
    stageLabel: (stage: number) => `שלב ${stage}`,
    moduleLabel: (module: number) => `מודול ${module}`,
    lockedTitle: "השיעור הזה עדיין נעול",
    lockedBody: "השיעורים נפתחים לפי הסדר. סיים את השיעור הקודם, ואם זה שלב חדש, עבור את השער.",
    unwrittenTitle: "השיעור הזה עוד לא נכתב",
    unwrittenBody: "התוכן בדרך. בינתיים אפשר לחזור על הכרטיסיות.",
    toRoadmap: "למפת הדרך",
    toQuiz: "לשאלות",
    quizIntro: "5 שאלות. עוברים עם 4 תשובות נכונות. אפשר לנסות שוב.",
    completed: "השיעור הושלם",
    completedBody: "הכרטיסיות של השיעור נכנסו לחפיסה.",
    nextLesson: "לשיעור הבא",
    toGate: "לשער השלב",
    retakeQuiz: "לשאלות שוב",
    readingProgress: "התקדמות בקריאה",
    verifiedOn: (date: string) => `אומת ב-${date}`,
    staleFact: "העובדה הזו לא נבדקה יותר מ-90 יום",
    volatileBanner: (date: string) => `השיעור כולל עובדות שמתעדכנות. נבדקו לאחרונה ב-${date}.`,
    volatileStale: "עברו יותר מ-90 יום מהבדיקה האחרונה. ייתכן שחלק מהפרטים השתנו.",
    sources: "מקורות",
    accessed: (date: string) => `נצפה ב-${date}`,
    previewBadge: "תצוגה מקדימה",
    callout: { warn: "שים לב", tip: "טיפ", note: "הערה" },
    widgetPlaceholderTitle: (name: string) => `הכלי ${name} עוד לא נבנה`,
    widgetPlaceholderBody: (phase: number) => `הוא ייבנה בשלב בנייה ${phase}. בינתיים קרא את ההוראה למטה ודמיין את התרגול.`,
    widgetUnknown: (name: string) => `כלי לא מוכר: ${name}`,
    exerciseMissing: (id: string) => `התרגיל ${id} לא נמצא`,
  },
  quiz: {
    title: "שאלות",
    heading: (lesson: string) => `שאלות: ${lesson}`,
    question: (n: number, total: number) => `שאלה ${n} מתוך ${total}`,
    check: "בדוק",
    next: "לשאלה הבאה",
    finish: "לתוצאה",
    numericLabel: "התשובה שלך",
    numericPlaceholder: "הקלד מספר",
    correct: "נכון.",
    wrong: "לא נכון.",
    correctAnswerWas: "התשובה הנכונה:",
    resultTitle: "התוצאה",
    score: (correct: number, total: number) => `${correct} מתוך ${total}`,
    passed: "עברת. השיעור הושלם.",
    failed: "עדיין לא. צריך 4 תשובות נכונות. נסה שוב, השאלות יוצגו בסדר אחר.",
    retry: "נסה שוב",
    saving: "שומר את התוצאה...",
    saveFailed: "התוצאה לא נשמרה. בדוק את החיבור ונסה שוב.",
    previewNote: "במצב תצוגה התוצאה לא נשמרת.",
    backToLesson: "חזרה לשיעור",
  },
  cards: {
    title: "כרטיסיות",
    due: (n: number) => (n === 1 ? "כרטיסייה אחת לחזרה" : `${n} כרטיסיות לחזרה`),
    remaining: (n: number) => `נשארו ${n}`,
    showAnswer: "הצג תשובה",
    knew: "ידעתי",
    didNot: "לא ידעתי",
    box: (n: number) => `קופסה ${n}`,
    noneDue: "אין כרטיסיות לחזרה היום",
    noneDueBody: (next: string | null, total: number) =>
      total === 0
        ? "הכרטיסיות הראשונות ייכנסו לחפיסה כשתסיים שיעור."
        : next
          ? `יש לך ${total} כרטיסיות בחפיסה. הבאה מחכה ב-${next}.`
          : `יש לך ${total} כרטיסיות בחפיסה.`,
    doneTitle: "סיימת את החזרה להיום",
    doneBody: (knew: number, total: number) => `ידעת ${knew} מתוך ${total}. מה שלא ידעת חוזר לקופסה 1 ויופיע שוב מחר.`,
    fromLesson: (title: string) => `מהשיעור: ${title}`,
    toToday: "למסך היום",
    cardOf: (n: number, total: number) => `כרטיסייה ${n} מתוך ${total}`,
  },
  glossary: {
    title: "מילון מונחים",
    intro: "כל מונח, בעברית ובאנגלית, עם הסבר במשפט אחד ואיפה לומדים אותו.",
    search: "חיפוש מונח",
    searchPlaceholder: "למשל: מרווח, Spread",
    count: (n: number) => (n === 1 ? "מונח אחד" : `${n} מונחים`),
    noResults: "לא נמצא מונח כזה.",
    taughtIn: "נלמד בשיעור",
    notYetWritten: "השיעור עוד לא נכתב",
    termLink: "למילון",
    termTooltip: "הסבר למונח",
  },
  gate: {
    title: (stage: number) => `שער שלב ${stage}`,
    intro: "השער בודק שאתה מוכן לשלב הבא. שני חלקים: מבחן ומשימה. שניהם חובה.",
    lockedTitle: "השער עוד נעול",
    lockedBody: "סיים את כל שיעורי השלב ואז חזור לכאן.",
    passedTitle: "עברת את השער",
    passedBody: (stage: number) => `שלב ${stage} פתוח. מפת הדרך מראה את השיעור הבא.`,
    requirement: {
      exam: "מבחן",
      contract: "חוזה לימוד",
      task: "משימה",
      drill: "תרגיל זיהוי",
      sizing: "גודל פוזיציה ביד",
      style: "בחירת סגנון",
      strategy: "כרטיס אסטרטגיה",
      backtest: "בדיקה לאחור",
      plan: "תוכנית מסחר",
      checklist: "רשימת בדיקה",
      limits: "כללי עצירה",
      demo: "מסחר דמו",
    } as Record<string, string>,
    examIntro: (n: number, pass: number) => `${n} שאלות מכל שיעורי השלב. עוברים עם ${pass}% ומעלה. אפשר לנסות שוב.`,
    examStart: "התחל מבחן",
    examPassed: (score: number) => `עברת את המבחן עם ${score}%.`,
    examFailed: (score: number, pass: number) => `הציון: ${score}%. צריך ${pass}%. נסה שוב, השאלות יוגרלו מחדש.`,
    examRetry: "מבחן חדש",
    later: (phase: number) => `החלק הזה ייבנה בשלב בנייה ${phase}.`,
    contractTitle: "חוזה לימוד",
    contractIntro: "לפני שממשיכים, שני דברים בכתב.",
    contractBudgetLabel: "סכום הלימוד שלי, בשקלים",
    contractBudgetHelp: "הסכום שחישבת בשיעור 4. כסף שמותר לך להפסיד כולו.",
    contractBudgetInvalid: "הקלד סכום שלם, 0 או יותר.",
    contractNoRealMoney: "אני מתחייב לא לסחור בכסף אמיתי לפני שאעבור את שער שלב 7.",
    contractBudgetWritten: "קבעתי סכום לימוד כתוב, והוא כסף שאובדנו לא ישנה את חיי.",
    contractSign: "חתום",
    contractSigned: (date: string) => `נחתם ב-${date}`,
    contractMustAgree: "צריך לסמן את שתי ההתחייבויות.",
    evidenceTitle: "ראיות למשימה",
    evidenceText: "מה עשית, במילים שלך",
    evidenceTextPlaceholder: "כתוב כאן את הניתוח או את תיאור הביצוע.",
    evidenceFile: "צילום מסך (לא חובה)",
    evidenceFileHelp: "PNG או JPG עד 5MB. נשמר בתיקייה הפרטית שלך.",
    evidenceSubmit: "שלח",
    evidenceTooShort: "כתוב לפחות 20 תווים.",
    evidenceSaved: (date: string) => `הוגש ב-${date}`,
    uploadFailed: "העלאת הקובץ נכשלה.",
  },
  exercise: {
    progress: (n: number, total: number) => `${n} מתוך ${total}`,
    resultTitle: "סיימת",
    score: (correct: number, total: number) => `${correct} מתוך ${total} נכונות`,
    sortPrompt: "לאיזו קבוצה זה שייך?",
    matchPrompt: "מה מתאים?",
    trueLabel: "נכון",
    falseLabel: "לא נכון",
    guessLabel: "הניחוש שלך",
    guessActual: "הנתון האמיתי",
    guessClose: "קרוב.",
    guessFar: (diff: string) => `הפער: ${diff}.`,
    guessAverageGap: (gap: string) => `הפער הממוצע בין הניחושים שלך לנתונים: ${gap}`,
    source: "מקור",
    scenarioPrompt: "מה תעשה?",
    yourAnswer: "ענית:",
  },
  widgets: {
    tour: {
      title: "סיור במערכת",
      steps: [
        { title: "היום", body: "המסך הראשון בכל כניסה. הוא עונה על שאלה אחת: מה הצעד הבא שלך. השיעור הבא, כרטיסיות שמחכות, והיעד השבועי." },
        { title: "מפת דרך", body: "כל השלבים והשיעורים, מהראשון לאחרון. ירוק הושלם, פתוח זמין, אפור נעול. בסוף כל שלב יש שער." },
        { title: "שיעור", body: "20 דקות קריאה עם תרגול באמצע. מונח שמופיע בעברית ובאנגלית אפשר ללחוץ עליו ולקבל הסבר. בסוף, 5 שאלות." },
        { title: "כרטיסיות", body: "אחרי כל שיעור נכנסות 3 עד 4 כרטיסיות לחפיסה. כרטיסייה שידעת מתרחקת, כרטיסייה שלא ידעת חוזרת למחר." },
        { title: "שער", body: "מבחן מכל שיעורי השלב ומשימה מעשית. השלב הבא נשאר נעול עד ששניהם מסומנים." },
        { title: "מעבדה ויומן", body: "המעבדה מתמלאת בכלי תרגול משלב 1. היומן נפתח בשלב 5 ומלווה כל עסקה בדמו." },
      ],
      finished: "סיימת את הסיור. השיעור הבא מופיע במסך היום ברגע שתעבור את השאלות.",
      stepOf: (n: number, total: number) => `${n} מתוך ${total}`,
    },
    budget: {
      title: "מחשבון סכום לימוד",
      income: "הכנסה חודשית נטו",
      expenses: "הוצאות חודשיות",
      savings: "חיסכון נזיל",
      months: "חודשי קרן חירום",
      ils: "₪",
      resultTitle: "סכום הלימוד המרבי",
      limitedByFund: "מה שמגביל אותך: מה שנשאר אחרי קרן החירום.",
      limitedByRebuild: "מה שמגביל אותך: מה שתוכל לבנות מחדש בשלושה חודשים.",
      limitedByNone: "שתי התקרות שוות.",
      zeroBody: "קודם קרן חירום. כשהחיסכון יעבור את הקרן, יהיה מה לחשב.",
      stepsTitle: "החישוב, שלב אחרי שלב",
      saveAsBudget: "שמור כסכום הלימוד שלי",
      savedBudget: (n: string) => `נשמר: ${n} ₪. תאשר אותו שוב בחוזה הלימוד בשער.`,
      lessThanMax: "אפשר לבחור פחות מהמרבי. לא יותר.",
      notFinancialAdvice: "כלי לחשיבה, לא הוראה. המספרים 3 ו-4 הם מוסכמה, לא חוק.",
    },
  },
  lab: {
    title: "מעבדה",
    empty: "כלי התרגול יופיעו כאן.",
    intro: "כלי התרגול של הקורס. כל כלי מופיע בשיעור שלו וגם כאן.",
    built: "זמין",
    planned: "בבנייה",
    exercises: "תרגילים",
    exercisesIntro: "תרגילים משיעורי שלב 0. אפשר לחזור עליהם בלי לפתוח את השיעור.",
    openLesson: "לשיעור",
  },
  journal: { title: "יומן", empty: "יומן העסקאות יופיע כאן." },
  signIn: {
    title: "כניסה",
    intro: "הקלד את כתובת המייל שלך. נשלח אליה קישור כניסה, בלי סיסמה.",
    emailLabel: "כתובת מייל",
    submit: "שלח לי קישור",
    sending: "שולח...",
    sent: "שלחנו קישור כניסה. פתח את המייל ולחץ עליו.",
    invalidEmail: "כתובת המייל לא תקינה.",
    failed: "לא הצלחנו לשלוח את הקישור. נסה שוב בעוד דקה.",
    linkFailed: "קישור הכניסה לא תקף או שפג תוקפו. בקש קישור חדש.",
    notConfigured: "המערכת עדיין לא מחוברת לבסיס הנתונים. חסרים משתני סביבה של Supabase.",
  },
} as const;
